### ISSUE TITLE
Keyboard events for InputBox

### ISSUE THREAD

**Issue by INeedAUniqueUsername** [SadConsole/SadConsole#144]
Would it be a good idea to add keyboard events to a focused InputBox? This is mainly for convenience so that I don't need to have the parent handle them. I'd also like to prevent the InputBox from always toggling keyboard when Enter is pressed

**Comment by Thraka** [comment]
Something other than the `TextChanged` event on the control? Like you want a `keypress` event?

**Comment by INeedAUniqueUsername** [comment]
I just extended the InputBox and added an optional Func<Keyboard, bool> member to catch the up/down arrow key and Enter key presses, which TextChange doesn't catch.
