### ISSUE TITLE
InputBox Caret Position always resets to last character

### ISSUE THREAD

**Issue by INeedAUniqueUsername** [SadConsole/SadConsole#145]
The arrow keys on the InputBox don't work at all because ValidateEdit() calls PositionCursor(), which always resets the caret to the last character. I'm found the bug while using the NuGet release but I see the error in the current source code.

https://github.com/Thraka/SadConsole/blob/9d3d9ee22edef7e61f841c1164b43e1be4a291a4/src/SadConsole.Shared/Controls/InputBox.cs#L315

**Comment by Thraka** [comment]
thanks! this used to work and i haven't taken the time to investigate it.

**Comment by Thraka** [comment]
I think I need to rethink the textbox design. It's a little too fragile at the moment with trying to fix this bug.

**Comment by SadConsole** [comment]
This was fixed in #183 !! Thanks @darrellp
