### ISSUE TITLE
Inputbox hidding password

### ISSUE THREAD

**Issue by darkfriend77** [SadConsole/SadConsole#157]
Hi,

currently using a textbox to get in a password verification, is there a way to have the password represented by asterix in visual?

*****
![wallet_password](https://user-images.githubusercontent.com/17710198/47425637-3f772900-d78b-11e8-8ccb-1e46f558fdad.png)

**Comment by Thraka** [comment]
I have thought about adding this. I'll see what I can do.

**Comment by darkfriend77** [comment]
Thank you.

**Comment by philipbawn** [comment]
I would like this feature also. :)

**Comment by philipbawn** [comment]
I implemented this and submitted PR #203 for reference

**Comment by SadConsole** [comment]
@philipbawn Thanks for adding this!
