### ISSUE TITLE
Please document how to get started with .NET Core

### ISSUE THREAD

**Issue by nightblade9** [SadConsole/SadConsole#167]
As discussed in [this issue](https://github.com/SadConsole/SadConsole/issues/137#issuecomment-441820381). It looks like the current steps are:

1) Install the (unofficial as of 3.6) MonoGame template:

```
dotnet new --install MonoGame.Template.CSharp

# in directory where you want to create the project
dotnet new mgdesktopgl
dotnet run
```

2) Install the NuGet package `SadConsole.Standard`

3) Profit

**Comment by SadConsole** [comment]
Finished. We're testing it but I ran through it and didn't have a problem 😄 

http://sadconsole.com/docs/getting-started-sadconsole-core-standard.html
