### ISSUE TITLE
There is no easy way to resize the window and backbuffer at runtime

### ISSUE THREAD

**Issue by AdrienKYoung** [SadConsole/SadConsole#204]
At the moment, resizing the SadConsole window requires the user to set the backbuffer and window size, then manually call GraphicsDeviceManager.ApplyChanges() and ResetRendering(). It would be nice for users to not have to duplicate this logic. 

The following is a working example of the task from my own code that sets the window size to the screen size (thanks to Thraka for providing the basic outline and helping to debug it):

```
              var mode = GraphicsAdapter.DefaultAdapter
                    .SupportedDisplayModes
                    .OrderByDescending(dm => dm.Width)
                    .First();

                root = new SadConsole.Console(
                    mode.Width / Global.FontDefault.Size.X, 
                    mode.Height / Global.FontDefault.Size.Y);
                Global.CurrentScreen = root;

                Global.GraphicsDeviceManager.PreferredBackBufferWidth = mode.Width;
                Global.GraphicsDeviceManager.PreferredBackBufferHeight = mode.Height;
                Global.GraphicsDeviceManager.ApplyChanges();

                Global.WindowWidth = mode.Width;
                Global.WindowHeight = mode.Height;
                Global.ResetRendering();
```

**Comment by SadConsole** [comment]
Thanks, I got this fixed! It will be in the next release. I added `Global.Settings.ResizeWindow`
