### ISSUE TITLE
Positioning for different font sizes

### ISSUE THREAD

**Issue by manf88** [SadConsole/SadConsole#209]
https://www.reddit.com/r/sadconsole/comments/asqp20/font_size_and_relative_positions_in_a_console/

Hi Folks,

i'm stuck with a problem here. I try to create a little console, which is separated into three areas. One at the top left, one at the top right and one along the button. In every of this areas i want to display text in different sizes. I use the FontMaster to change the size of a particular console and it works quite well. However, if i try to set the positions of the text, everything seems to be messed up. Or, which is more probable, i just don't get it.

I would expect that the position of a console is relative to its parent, but it seems like the position is relative to the main console and recalculated by the current font size.  Therefore, the text has an more or less unpredictable offset.

It's kind of hard to explain and maybe i'm getting it wrong, so i wrote a little program to picture the problem.

````
using Microsoft.Xna.Framework;
using SadConsole;

namespace Digifiz
{
    internal class FontSizeTest : Console
    {
        private Console _console1;
        private Console _console2;

        private Console _console11;
        private Console _console21;

        public FontSizeTest(int width, int height) : base(width, height)
        {
            _console1 = new Console(10, 10);
            _console1.Fill(Color.Blue, Color.Beige, null);
            _console2 = new Console(10, 10);
            _console2.Fill(Color.Green, Color.Red, null);
            _console2.Position = new Point(10, 0);

            _console11 = new Console(6, 5);
            _console11.Fill(Color.Blue, Color.Magenta, null);
            _console1.Children.Add(_console11);

            _console21 = new Console(6, 5);
            _console21.Fill(Color.Green, Color.Yellow, null);
            _console2.Children.Add(_console21);

            FontMaster fontMaster = Global.LoadFont("C64.font");

            _console11.Font = fontMaster.GetFont(Font.FontSizes.One);
            _console11.Print(1, 1, "test1");

            _console21.Font = fontMaster.GetFont(Font.FontSizes.Two);
            _console21.Print(0, 0, "test2");

            Children.Add(_console1);
            Children.Add(_console2);
        }
    }
}
````
As you can see i changed the font size of one of the inner consoles (_console21) to "Two" and afterwards it's position is not inside it's parent anymore. If you change the FontSize to "One" again, everything is as expected.

I'm not sure if i'm doing anything wrong or it is intended and i just don't get the logic behind it, but any help is highly appreciated!

**Comment by SadConsole** [comment]
I actually just fixed this in the v8 code base commit ce522d9 but it's not been uploaded to nuget yet. I can do a release today. If you're not using the v8 pre-release, you should be. There are a number of breaking changes and things renamed, it's close to being released, so if you just start with v8, you won't have anything to migrate 😄 

Quickly explaining, the positioning is always in cells. Each console sees the world in those cell sizes, which is based on the console font width and height. The parent-child relationship has the child say:

- What is my position? (10, 10)
- Add my parent's position to that. (5, 5)
- Add my parent's-parent position to that (1, 1)
- ... continue pulling parent positions.
- Convert that final position to a pixel position.

If a parent or child had a different font, it console A is quite different from console B from the pixel position. What this code change does is this:

- What is my position?
- Convert that to pixels
- Add my parent's PIXEL position to that.
- Add my parent's-parent PIXEL position to that.
- ... continue pulling parent PIXEL positions.
