### ISSUE TITLE
Changing Game Icon on .NET Core Project

### ISSUE THREAD

**Issue by nightblade9** [SadConsole/SadConsole#219]
Me again. I asked for .NET Core support (#137) and created a project using your template (#167). Now, I'm stuck trying to set the app icon.

I can't figure out where the default MonoGame icon comes from. I searched the web (MonoGame, .NET Core, both, separately, etc.) I think adding this to the first `PropertyGroup` in my `.csproj` should work, but I still see the MonoGame icon:

`<ApplicationIcon>icon.ico</ApplicationIcon>`

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <VersionPrefix>1.0.0</VersionPrefix>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
```

Can you please let me know how I can change my game icon?

You can find my repo [here](https://github.com/deengames/ali-the-android) on GitHub.

**Comment by SadConsole** [comment]
Thanks for the question.

`ApplicationIcon` is only supported on .NET Core 3.0. Change your target framework and make sure you've installed the 3.0 preview SDK.

```xml
<TargetFramework>netcoreapp3.0</TargetFramework>
```

**Comment by nightblade9** [comment]
Where did you find this information? I couldn't find anything about app icons :(

Also ... this means I have to re-test my entire game! Good thing I'm close to doing pre-release testing, then :thinking: 

Will try this and comment back if/when it works.
