### ISSUE TITLE
Guide to graphical tiles

### ISSUE THREAD

**Issue by nightblade9** [SadConsole/SadConsole#222]
![image](https://user-images.githubusercontent.com/31222662/64921579-ecd3a080-d792-11e9-905d-c3aa8e65db2d.png)

I found out quite late in development (the day before shipping my game) that SadConsole works with graphical (1-bit) tiles. I would like to draft up a guide for doing this. Namely, the process (make the game with ASCII first, implement a camera via a back-buffer console, create an empty grid, start populating tiles on their ASCII positions).

Please let me know where/how I can contribute this.

**Comment by SadConsole** [comment]
Sure! You would want to file a PR against the website repo, specifically the source folder. You can see some existing articles here: https://github.com/Thraka/thraka.github.io/tree/source/articles

It's in markdown format, which is extremely simple to learn. Look at the existing article to understand the format and structure.

**Comment by nightblade9** [comment]
I haven't forgotten about this. I hope to get to it tomorrow.

**Comment by nightblade9** [comment]
Initial draft available here: https://github.com/Thraka/thraka.github.io/pull/2

**Comment by nightblade9** [comment]
Is it possible to get some feedback on this? It's been open for a week so far.

@Thraka @SadConsole

**Comment by SadConsole** [comment]
Thanks, I've left review comments on the PR. Awesome job!

**Comment by nightblade9** [comment]
Thanks for the detailed review. I'm going to close this since the work is basically done. Feel free to re-open if I missed something.
