### ISSUE TITLE
LoadFonts() does not work in V9

### ISSUE THREAD

**Issue by coldwarrl** [SadConsole/SadConsole#229]
LoadFont() in SadConsole.Gamehost() does not work. The issue is the Json serializer.

If you comment out in SadConsole.Serializer
```
 //_settings.ContractResolver = new Contracts();
```

it will work, I have not checked if this is needed in other Serialization usecase.

**Comment by SadConsole** [comment]
Fixed in the next NuGet release (today) Thanks!
