### ISSUE TITLE
Discord Server Invite

### ISSUE THREAD

**Issue by markjamesm** [SadConsole/SadConsole#239]
Is the Discord server still active? Whenever I try to use the invite link I've found around the web Discord says that the invite is no longer valid.

**Comment by Chris3606** [comment]
It's definitely still active, the link must have been broken somewhere -- I'm sure @Thraka can generate another permanent one, however in the meantime (expires in 1 day): https://discord.gg/KfMDUW

**Comment by markjamesm** [comment]
Thanks Chris! I just tried the link but am getting the following error:

<img width="512" alt="Screen Shot 2020-05-18 at 9 31 34 PM" src="https://user-images.githubusercontent.com/20845425/82274745-f3806c00-994e-11ea-93c7-1a53df231132.png">

Maybe the server needs a setting changed? @Thraka can you confirm?

**Comment by Thraka** [comment]
Here is a link I've generated that should never expire. Try this one: https://discord.gg/TagZMGg

**Comment by markjamesm** [comment]
Works! Many thanks!
