### ISSUE TITLE
The "GetMGCBTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by aodendaal** [SadConsole/SadConsole#240]
- Following the tutorial **Create a new SadConsole .NET Core project**
- Installed MonoGame 3.7.1
- Created a new directory for a game
- Ran `dotnet new --install MonoGame.Template.CSharp`
- Ran `dotnet new mgdesktopgl`
- Ran `dotnet run`

Expected:
A MonoGame window with the default background

Actual:
`error MSB4018: The "GetMGCBTask" task failed unexpectedly.`

*I know this isn't strictly a SadConsole issue, but I'm following the tutorial on the SadConsole website*

**Comment by aodendaal** [comment]
According to @harry-cpp there are no dotnet templates for 3.7 and MonoGame.Template.CSharp should not be used.

**Comment by SadConsole** [comment]
@aodendaal They must have changed the templates. However, I did publish my own templates. I should remove the article you were using. Please use this one instead: http://sadconsole.com/articles/getting-started-sadconsole-core-cli-template.html

**Comment by harry-cpp** [comment]
I published few of the packages myself until 3.8 got around. Now several of them have been killed/replaced:
- MonoGame.Template.CSharp -> MonoGame.Templates.CSharp
- MonoGame.Content.Builder -> MonoGame.Content.Builder.Task
- MonoGame.Framework.DesktopGL.Core -> MonoGame.Framework.DesktopGL
- MonoGame.Framework.WindowsDX.Core -> MonoGame.Framework.WindowsDX

**Comment by harry-cpp** [comment]
Also love your console, I'm writing something similar myself, for my own game.
