### ISSUE TITLE
Game.Create width when using a square font

### ISSUE THREAD

**Issue by DaveSprague** [SadConsole/SadConsole#241]
I've gone through "How a Font works" on the SadConsole website (https://sadconsole.com/articles/basic-font-information.html) and I have it working with a square font wanted to try.  The font is a 16 x 16 pixel square font. 

To test the font,  I'm creating a 16 x 16 console and populating it with an array of Cells with the Glyph property set to incrementing values from 0 - 255.

```
using System;
using SadConsole;
using Microsoft.Xna.Framework;
using Console = SadConsole.Console;

namespace sadconsolefonttest
{
    class Program
    {
        static void Main()
        {
            // Setup the engine and create the main window.
            SadConsole.Game.Create(16, 16); // <--- **** I need to change this to (32, 16) to work correctly ****

            // Hook the start event so we can add consoles to the system.
            SadConsole.Game.OnInitialize = Init;

            // Start the game.
            SadConsole.Game.Instance.Run();
            SadConsole.Game.Instance.Dispose();
        }

        static void Init()
        {
            Cell[] map = new Cell[256];
            for (int gly = 0; gly < 256; gly++)
            {
                map[gly] = new Cell(Color.White, Color.Gray, gly);
            }

            var fontMaster = SadConsole.Global.LoadFont(@"Font\16x16_sm_ascii.font");
            var normalFont = fontMaster.GetFont(SadConsole.Font.FontSizes.One);
            var bigFont = fontMaster.GetFont(SadConsole.Font.FontSizes.Two);
            var console = new Console(16, 16, normalFont, map);
            // var console = new Console(16, 16, Global.FontDefault, map);
            // var console = new Console(16, 16);
            // console.FillWithRandomGarbage();

            SadConsole.Global.CurrentScreen = console;
        }
    }
}
```

When I run the program with both the Game.Create width and the new Console width set to 16, then I only get a 8 character wide console. 

![Using Game Create width of 16](https://user-images.githubusercontent.com/1448202/85634435-5f8a7a00-b649-11ea-97ac-e7010f2477e5.png)

 I have to bump up the Game Create width to 32 while keeping the new Console width at 16 in order for it to display the full 16 character wide window.

![Using Game Create Width of 32](https://user-images.githubusercontent.com/1448202/85634441-63b69780-b649-11ea-963d-e2c9c7d4c0ec.png)

This is the content of the .font file:
```
{
  "Name": "16x16_sm_ascii",
  "FilePath": "16x16_sm_ascii.png",
  "GlyphHeight": 16,
  "GlyphPadding": 0,
  "GlyphWidth": 16,
  "SolidGlyphIndex": 219,
  "Columns": 16,
  "IsSadExtended": false
}
```

And here is a link to the png file for the font.

https://1drv.ms/u/s!AhHT7_5wGG0VkskyQ_OYKiRMLvCHtw?e=DOrbDb

Here's a screenshot I took of it. For some reason, when I try to embed the png image here, it shows as all white or all transparent so you can't see it.

![image](https://user-images.githubusercontent.com/1448202/85635967-34098e80-b64d-11ea-896f-e5c8bf39203b.png)

**Comment by SadConsole** [comment]
Hello! The create width/height is how many cells the window will show based on the default font size, which is 8x16 pixels. When you change the default font in `Init`, it's window size was already determined, based on default font. The `Create` method actually has a parameter for you to pass in `"Font\16x16_sm_ascii.font"` as the new "default" font and then sizes the window according to that.

```csharp
SadConsole.Game.Create("Font\16x16_sm_ascii.font", 16, 16);
```

That should fix your problem. That also sets the `SadConsole.Global.FontDefault` to your provided font and all consoles created that don't specify a font will use that font.

Let me know if this fixes your problem! Feel free to join us on discord too!

**Comment by DaveSprague** [comment]
Okay, that makes sense.  Thanks,

Dave
