### ISSUE TITLE
Format exception in ParseCommandBlink

### ISSUE THREAD

**Issue by Warspider** [SadConsole/SadConsole#84]
Hello Thraka.
Found some format exception in DemoProject while run app using os with not english default culture.
Problem in ParseCommandBlink class in double.Parse function, because it use culture-specific dot.
Suggest an option to fix error - add format provider like 
`double.Parse(parametersArray[1], System.Globalization.CultureInfo.InvariantCulture);`
os windows 10
```
System.FormatException: Входная строка имела неверный формат.
   в System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   в System.Double.Parse(String s)
   в SadConsole.StringParser.ParseCommandBlink..ctor(String parameters, ColoredGlyph[] glyphString, ParseCommandStacks commandStack, SurfaceEditor surfaceEditor) в D:\my\SadConsole\src\SadConsole.Shared\StringParser\ParseCommandBlink.cs:строка 22
   в SadConsole.ColoredString.Parse(String value, Int32 surfaceIndex, ISurface surface, SurfaceEditor editor, ParseCommandStacks initialBehaviors) в D:\my\SadConsole\src\SadConsole.Shared\ColoredString.Commands.cs:строка 81
```
Pretty simple small contributing to the interesting library.

**Comment by Thraka** [comment]
Thanks! It's one of those things I just never think about, but is important.

**Comment by Thraka** [comment]
@Warspider I don't think this is technically a problem. If you look at the documentation for [Double.Parse](https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?view=netframework-4.7.1#System_Double_Parse_System_String_) it says this:

>The s parameter is interpreted using the formatting information in a NumberFormatInfo object that is initialized for the current thread culture. For more information, see CurrentInfo. To parse a string using the formatting information of some other culture, call the Double.Parse(String, IFormatProvider) or Double.Parse(String, NumberStyles, IFormatProvider) method. 

According to that, the thread you're running should dictate the parsing culture, which is then probably set by your operating system language settings or something, and it's set to english while you're passing a different string?
